// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/landru29/gospot/internal/app"
)

// Injectors from setup_app.go:

func setupApplication(conf *app.Config, toLaunch apiList) (*app.Controller, func(), error) {
	fieldLogger := provideLogger()
	v, err := providePublicAPI(fieldLogger, conf, toLaunch)
	if err != nil {
		return nil, nil, err
	}
	controller, err := app.New(conf, fieldLogger, v...)
	if err != nil {
		return nil, nil, err
	}
	return controller, func() {
	}, nil
}
